name: 'Action Go Report Card'
description: 'Generate Go Report Card'
inputs:
  threshold:
    description: "threshold for failure (-t)"
    required: false
    default: "-t 0"
  verbose:
    description: "verbose mode (-v)"
    required: false
    default: ""
outputs:
  summary:
    description: "Go Report Card Output"
    value: ${{ steps.goreportcard.outputs.summary }}

runs:
  using: "composite"
  steps:
    - name: Go Report Card
      id: goreportcard
      run: |
        go get -u github.com/client9/misspell/cmd/misspell
        git clone https://github.com/gojp/goreportcard.git
        cd goreportcard
        make install
        go install ./cmd/goreportcard-cli
        cd .. && rm -rf goreportcard
        goreportcard-cli ${{ inputs.verbose }} ${{ inputs.threshold }}
        output=`goreportcard-cli ${{ inputs.verbose }} ${{ inputs.threshold }}`
        output="${output//'%'/'%25'}"
        output="${output//$'\n'/'%0A'}"
        output="${output//$'\r'/'%0D'}"
        echo "::set-output name=summary::${output}"
      shell: bash

